-- Generated by nwg-displays on 2026-06-19 at 13:05:23. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1600x900@59.67",
    position = "0x0",
    scale = 1.0
})
